name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: chmod
      run: chmod 777 configure
    - name: configure
      run: ./configure
    - name: make
      run: make
